<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\rtaime.Core\rtaime.Core.csproj" />
    <ProjectReference Include="..\..\Contracts\rtaime.AI.Contracts\rtaime.AI.Contracts.csproj" />
    <ProjectReference Include="..\..\Contracts\rtaime.Media.Contracts\rtaime.Media.Contracts.csproj" />
    <ProjectReference Include="..\..\Contracts\rtaime.Provider.Contracts\rtaime.Provider.Contracts.csproj" />
  </ItemGroup>
</Project>
