<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Client\rtaime.Client\rtaime.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="rtaime.Tests.Unit" />
    <InternalsVisibleTo Include="rtaime.Tests.Integration" />
    <InternalsVisibleTo Include="rtaime.Tests.Failure" />
  </ItemGroup>
</Project>
