<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>$(RtaimeWindowsTargetFramework)</TargetFramework>
		<UseWPF>true</UseWPF>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Client\rtaime.Client\rtaime.Client.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="DemoAssets\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
