<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>$(RtaimeWindowsTargetFramework)</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Client\rtaime.Client\rtaime.Client.csproj" />
	</ItemGroup>
</Project>
